### ISSUE TITLE
Toggle toolbars is dependant on the user hovering over the button

### ISSUE THREAD

**Issue by callinmullaney** [jacerider/escort#22]
Add a toggle bottom escort to the top toolbar with a hover or click setting. The toolbar will only show if I hover/click the toggle. As soon as my mouse hovers off the toggle, the bottom toolbar will hide.

**Comment by jacerider** [comment]
I fixed this issue. I also added the correct .is-active class to open toggle elements and it looks like some styling tweaks are needed.

**Comment by callinmullaney** [comment]
Padding issue has been fixed for toggle in horizontal toolbars
