### ISSUE TITLE
Review dropdown widget use/functionality

### ISSUE THREAD

**Issue by callinmullaney** [jacerider/escort#28]
When I want to add a dropdown widget I have an option to add plain text or markup in the 'dropdown content' field. This seems a little ambiguous on what I can and should use this widget for.

Maybe this should be removed and added as a display option for menu escorts? Or instead of the dropdown content field I have the option to embed links or even other escort widgets?

**Comment by jacerider** [comment]
This is simply a base plugin that several other plugins use to implement their dropdown functionality. I will hide it from the UI for now.
