### ISSUE TITLE
Breaks when running on Drupal 8.4.0.

### ISSUE THREAD

**Issue by dficker** [jacerider/escort#44]

**Comment by dficker** [comment]
I think I found the issue. The issue seems to stem around changes to DefaultSingleLazyPluginCollection class, which makes the collection no longer lazy.  It seems that the parent class call has to come at the end of the construct instead of the start?  At least that's what Entityqueue did.

https://www.drupal.org/node/2851635

**Comment by dficker** [comment]
Changed this in `src/EscortPluginCollection.php`:

```php
  public function __construct(PluginManagerInterface $manager, $instance_id, array $configuration, EscortInterface $escort) {
    parent::__construct($manager, $instance_id, $configuration);
    $this->escort = $escort;
  }
```

to

```php
  public function __construct(PluginManagerInterface $manager, $instance_id, array $configuration, EscortInterface $escort) {
    $this->escort = $escort;
    parent::__construct($manager, $instance_id, $configuration);
  }
```

It now seems to work on Drupal 8.4.0.

**Comment by jacerider** [comment]
Good catch @dficker. Thanks!
